# Generated by Django 2.0.1 on 2019-09-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_duration',
            field=models.CharField(default=None, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_instructor',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
    ]
