# Generated by Django 2.0.1 on 2019-09-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190918_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_duration',
            field=models.CharField(max_length=10),
        ),
    ]
