# Generated by Django 2.0.1 on 2019-09-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190919_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='lead_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_status', models.CharField(max_length=25)),
            ],
        ),
    ]
