# Generated by Django 2.0.1 on 2019-09-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_lead_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=25)),
                ('date', models.DateField(null=True)),
                ('course', models.CharField(max_length=25)),
                ('source', models.CharField(max_length=25)),
                ('lead_status', models.CharField(max_length=25)),
                ('counselor', models.CharField(max_length=25)),
                ('remarks', models.CharField(max_length=25)),
            ],
        ),
    ]
