# Generated by Django 2.0.1 on 2019-09-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='calling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calling', models.CharField(max_length=25)),
            ],
        ),
    ]
