# Generated by Django 2.0.1 on 2019-09-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_calling'),
    ]

    operations = [
        migrations.CreateModel(
            name='joining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('course', models.CharField(max_length=25)),
                ('date', models.DateField(null=True)),
                ('course_fee', models.CharField(max_length=7)),
                ('instructor', models.CharField(max_length=20)),
                ('aadhar', models.CharField(max_length=12)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=25)),
                ('remarks', models.CharField(max_length=25)),
            ],
        ),
    ]
