# Generated by Django 2.0.1 on 2019-09-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_joining_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joining',
            name='status',
            field=models.TextField(blank=True, max_length=25, null=True),
        ),
    ]
