# Generated by Django 2.0.1 on 2019-09-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20190928_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joining',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
